### ISSUE TITLE
Request feature: Delete tweets

### ISSUE THREAD

**Issue by FreedomLabsIO** [airhadoken/twitter-lib#25]
Is Tweet deletion on the roadmap?

**Comment by airhadoken** [comment]
Hi @brunoaduarte,

Because of Twitter's API changes that are hostile to bot developers, I'm no longer interested in adding features to Twitter Lib.  It's in a long-term maintenance phase now while I explore options for creating frameworks for Mastodon and other ActivityPub servers.

As a reminder, though, you can always use `.fetch()` with any endpoint in the API, and that includes POSTing to `statuses/destroy/:id` to delete tweets.  You can see the docs for that endpoint here: https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-destroy-id.html
