### ISSUE TITLE
Follow support

### ISSUE THREAD

**Issue by brubsby** [airhadoken/twitter-lib#26]
Doesn't seem like the API currently has support for following a user: https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/post-friendships-create

And maybe this as well to check whether you're friends first without trying to follow: https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-show

**Comment by airhadoken** [comment]
thanks for posting.  It's nice to know people are still using this library. However, two things you should know:

* Any REST endpoint in the Twitter API can be accessed through `.fetch()` -- the functions like sendTweet and fetchTweets in this library are only convenience functions on top of fetch.  In previous issues like #21 I show how fetch can be used for an endpoint without an associated convenience function.

* Development on this library is effectively finished, as I'm not interested in doing automation via the Twitter API anymore.  The difficulties that devs have in getting their projects on the platform are now too great.  I'm interested in doing similar libraries for distributed and federated platforms (e.g. the ActivityPub-speaking network including Mastodon) but I haven't started on that project.

**Comment by bigwheel** [comment]
@airhadoken 

> Development on this library is effectively finished,

Please archive this repository from https://github.com/airhadoken/twitter-lib/settings to avoid needless confusion.
It would take less than a minute.

**Comment by antgiant** [comment]
Adding a note here since I unarchived the API. I will continue to support this library and _may_ occassionally add features. (Pull requests always welcome.)

Having said that. I just looked into the "New" Twitter API v2 that requires OAuth 2.0. I will not ever be updating this library to support both. 

OAuth 2.0 requires a pretty fundamental rewriting of the authentication logic. Supporting it as a feature add is not possible for me. Perhaps someday someone will fork this library to create an OAuth 2.0 version or create a brand new equivalent. [Here's the library needed to get started on the fork idea.](https://github.com/googleworkspace/apps-script-oauth2) However, that is unlikely to be me unless Twitter totally kills the OAuth 1.0a API.

**Comment by airhadoken** [comment]
> Having said that. I just looked into the "New" Twitter API v2 that requires OAuth 2.0. I will not ever be updating this library to support both.

FWIW I endorse this opinion.  For one thing, I never liked going through the auth flow with the library and almost exclusively used it with pre-generated auth tokens.  I think the user experience is awful to authenticate through OAuth1 as is, and trying to do auth flows for both OAuth 1 and 2 would be a nightmare.

Twitter lib with OAuth2 should just be a separate library.  Full stop.  If anyone wants to try it, you have my blessing to fork the repo to create the OAuth2 version of Twitter lib.
